import {
  Smile,
  Zap,
  HelpCircle,
  Moon,
  Gamepad2,
  CloudRain,
  Focus,
  BatteryCharging,
  Heart,
  Sparkles,
} from "lucide-react";

export const MOODS = {
  happy: {
    label: "Happy",
    caption: "Just chilling.",
    accent: "#7fd6ff",
    glow: "rgba(127,214,255,0.55)",
    tint: "rgba(90,140,220,0.16)",
    icon: Smile,
    eye: "M6,29 Q30,6 54,29",
    fill: false,
    accessory: Heart,
    accessoryColor: "#ff9ecf",
  },
  excited: {
    label: "Excited",
    caption: "Let's go explore!",
    accent: "#ffd37d",
    glow: "rgba(255,211,125,0.55)",
    tint: "rgba(230,170,70,0.16)",
    icon: Zap,
    eye: "M16,8 L46,22 L16,36",
    fill: false,
    accessory: Sparkles,
    accessoryColor: "#ffd37d",
  },
  thinking: {
    label: "Thinking",
    caption: "Processing thoughts…",
    accent: "#b98cff",
    glow: "rgba(185,140,255,0.55)",
    tint: "rgba(140,110,220,0.16)",
    icon: HelpCircle,
    eye: "circle",
    fill: false,
    accessory: HelpCircle,
    accessoryColor: "#b98cff",
  },
  sleepy: {
    label: "Sleepy",
    caption: "Powering down…",
    accent: "#8fb0ff",
    glow: "rgba(143,176,255,0.45)",
    tint: "rgba(70,90,160,0.18)",
    icon: Moon,
    eye: "M8,22 Q30,29 52,22",
    fill: false,
    accessory: Moon,
    accessoryColor: "#a9c0ff",
  },
  playful: {
    label: "Playful",
    caption: "Play mode engaged.",
    accent: "#ff9ecf",
    glow: "rgba(255,158,207,0.55)",
    tint: "rgba(220,110,170,0.16)",
    icon: Gamepad2,
    eye: "M6,30 Q30,4 54,30",
    fill: false,
    accessory: Gamepad2,
    accessoryColor: "#ff9ecf",
  },
  sad: {
    label: "Sad",
    caption: "A little rainy today.",
    accent: "#8ea3d6",
    glow: "rgba(142,163,214,0.45)",
    tint: "rgba(70,85,130,0.2)",
    icon: CloudRain,
    eye: "M6,15 Q30,38 54,15",
    fill: false,
    accessory: CloudRain,
    accessoryColor: "#a9bce0",
  },
  focused: {
    label: "Focused",
    caption: "Deep in focus.",
    accent: "#7dffc0",
    glow: "rgba(125,255,192,0.5)",
    tint: "rgba(70,180,140,0.16)",
    icon: Focus,
    eye: "circle",
    glasses: true,
    fill: false,
    accessory: Focus,
    accessoryColor: "#7dffc0",
  },
  charging: {
    label: "Charging",
    caption: "Refueling energy.",
    accent: "#7dd8ff",
    glow: "rgba(125,216,255,0.55)",
    tint: "rgba(70,150,220,0.2)",
    icon: BatteryCharging,
    eye: "M8,23 Q30,29 52,23",
    fill: false,
    accessory: BatteryCharging,
    accessoryColor: "#7dd8ff",
  },
  love: {
    label: "In Love",
    caption: "Sending you love.",
    accent: "#ff6fa5",
    glow: "rgba(255,111,165,0.6)",
    tint: "rgba(230,90,150,0.2)",
    icon: Heart,
    eye: "heart",
    fill: true,
    accessory: Heart,
    accessoryColor: "#ff6fa5",
  },
};

export const MOOD_ORDER = [
  "happy",
  "excited",
  "thinking",
  "sleepy",
  "playful",
  "sad",
  "focused",
  "charging",
  "love",
];

export const SFX = {
  happy: { jp: "ピロリン♪", romaji: "Pirorin", fa: "صدای دلنشین شادی و آرامش" },
  excited: { jp: "キュイーン!", romaji: "Kyuīn!", fa: "صدای هیجان و انرژی زیاد" },
  thinking: { jp: "ウィーン…", romaji: "Uīn...", fa: "صدای پردازش و فکر کردن" },
  sleepy: { jp: "スースー…", romaji: "Sū sū...", fa: "صدای نفس آرام در خواب" },
  playful: { jp: "ピコピコ!", romaji: "Piko piko!", fa: "صدای بازیگوشی و شیطنت" },
  sad: { jp: "シュン…", romaji: "Shun...", fa: "صدای ناامیدی و دلگیری" },
  focused: { jp: "カチッ", romaji: "Kachi", fa: "صدای تمرکز و دقت کامل" },
  charging: { jp: "ピピピ…", romaji: "Pipipi...", fa: "صدای شارژ شدن باتری" },
  love: { jp: "ドキドキ♡", romaji: "Doki doki", fa: "صدای تپش قلب از عشق" },
};
